"use strict";
const fs=require("node:fs"),path=require("node:path");
const API_KEY=process.env.AIRNOW_API_KEY;
if(!API_KEY){console.error("AIRNOW_API_KEY is not configured.");process.exit(1)}
const locations=[["Badger Building Center", "Sagle", "ID", "83860", "Sandpoint Reporting Area"], ["Badger Building Center", "Post Falls", "ID", "83854", "Coeur d'Alene Reporting Area"], ["Badger Building Center", "Kalispell", "MT", "59901", null], ["Badger Building Center", "Bonners Ferry", "ID", "83805", null], ["Elma Building Center", "Elma", "WA", "98541", null], ["Beaverhead Building Center", "Dillon", "MT", "59725", null], ["Best Built Builders Supply", "Orofino", "ID", "83544", "Nez Perce Reservation"], ["Best Built Builders Supply", "Grangeville", "ID", "83530", "Grangeville Reporting Area"], ["Best Built Builders Supply", "Kamiah", "ID", "83536", null], ["Best Built Builders Supply", "Lewiston", "ID", "83501", "Lewiston Reporting Area"], ["Browne's Home Center", "Friday Harbor", "WA", "98250", null], ["Ennis Building Center", "Ennis", "MT", "59729", "Bozeman EBAM Monitor"], ["Gerretsen Building Supply", "Roseburg", "OR", "97470", null], ["Harbor Rental and Saw", "Friday Harbor", "WA", "98250", null], ["Lake Chelan Building Supply", "Chelan", "WA", "98816", "Chelan Reporting Area"], ["Lake Chelan Building Supply", "Manson", "WA", "98831", "Chelan Reporting Area"], ["Marson and Marson Lumber", "Leavenworth", "WA", "98826", "Leavenworth Reporting Area"], ["Marson and Marson Lumber", "Wenatchee", "WA", "98801", null], ["Marson and Marson Lumber", "Cle Elum", "WA", "98922", null], ["Marson and Marson Lumber", "Ephrata", "WA", "98823", null], ["Midway Building Supply", "Tonasket", "WA", "98855", null], ["Midway Building Supply", "Republic", "WA", "99166", "Republic Monitor"], ["Midway Building Supply", "Oroville", "WA", "98844", "Tonasket Monitor"], ["Miller's Home Center", "Baker City", "OR", "97814", null], ["Miller's Home Center", "La Grande", "OR", "97850", null], ["Mount Vernon Building Center", "Mount Vernon", "WA", "98273", null], ["TAL Support Center", "Vancouver", "WA", "98684", null], ["Tum-A-Lum Lumber", "Hood River", "OR", "97031", null], ["Tum-A-Lum Lumber", "The Dalles", "OR", "97058", null], ["Tum-A-Lum Lumber", "Pendleton", "OR", "97801", null]].map(([division,city,state,zip,preferredReportingArea])=>({division,city,state,zip,preferredReportingArea}));
const cachePath=path.join(process.cwd(),"cache","aqi-cache.json");
const norm=v=>String(v||"").toLowerCase().replace(/reporting area|monitor/g,"").replace(/[^a-z0-9]+/g," ").trim();
const source=x=>x.ReportingArea||x.reportingArea||x.ReportingAreaName||x.reportingAreaName||x.SiteName||x.siteName||null;
const aqi=x=>{for(const v of[x?.AQI,x?.aqi,x?.NowcastAQI,x?.nowcastAQI]){const n=Number(v);if(Number.isFinite(n))return n}return null};
const category=x=>{const c=x.Category??x.category;return typeof c==="object"?(c?.Name??c?.name??null):(c??x.CategoryName??x.categoryName??null)};
function oldCache(){try{return JSON.parse(fs.readFileSync(cachePath,"utf8"))}catch{return {locations:[]}}}
function oldReading(cache,l){return cache.locations?.find(x=>x.division===l.division&&x.city===l.city&&x.state===l.state&&String(x.zip)===l.zip)}
async function fetchOne(l){const q=new URLSearchParams({format:"application/json",zipCode:l.zip,distance:"50",API_KEY});const url=`https://www.airnowapi.org/aq/observation/current/zipCode/?${q}`;let response;for(let attempt=1;attempt<=3;attempt++){response=await fetch(url,{headers:{Accept:"application/json"}});if(response.ok)break;if(attempt<3)await new Promise(r=>setTimeout(r,attempt*1500))}if(!response.ok)throw new Error(`HTTP ${response.status}: ${(await response.text()).slice(0,160)}`);const body=await response.json(),all=Array.isArray(body)?body:[],wanted=norm(l.preferredReportingArea),matches=wanted?all.filter(x=>{const actual=norm(source(x));return actual&&(actual===wanted||actual.includes(wanted)||wanted.includes(actual))}):all,candidates=matches.length?matches:all,item=[...candidates].sort((a,b)=>(aqi(b)??-1)-(aqi(a)??-1))[0];if(!item)throw new Error("No current observation returned");const now=new Date().toISOString();return {...l,aqi:aqi(item),category:category(item)||"Observation available",pollutant:item.ParameterName||item.parameterName||null,reportingArea:source(item)||l.preferredReportingArea,observationDate:item.DateObserved||item.dateObserved||null,lastUpdated:now,error:wanted&&!matches.length?"Preferred source not found; nearest ZIP result shown":null}}
(async()=>{const old=oldCache(),results=[];for(const l of locations){try{results.push(await fetchOne(l))}catch(e){const prior=oldReading(old,l);results.push(prior?{...prior,...l,error:`Update failed; retained previous cache: ${e.message}`}:{...l,aqi:null,category:"Unavailable",pollutant:null,reportingArea:l.preferredReportingArea,observationDate:null,lastUpdated:null,error:e.message})}}const out={schemaVersion:1,lastUpdated:new Date().toISOString(),reporting:results.filter(x=>x.aqi!=null).length,elevated:results.filter(x=>x.aqi>100).length,status:"Updated by GitHub Actions",locations:results};fs.mkdirSync(path.dirname(cachePath),{recursive:true});fs.writeFileSync(cachePath,JSON.stringify(out,null,2)+"\n");console.log(`Updated ${out.reporting}/${results.length} locations`);if(!out.reporting)process.exitCode=1})().catch(e=>{console.error(e);process.exit(1)});
