"use strict";
const fs=require('node:fs'),path=require('node:path');
const key=process.env.AIRNOW_API_KEY;if(!key){console.error('AIRNOW_API_KEY is missing or empty');process.exit(1)}
const locations=[["Badger Building Center", "Sagle", "ID", "83860", "Sandpoint Reporting Area"], ["Badger Building Center", "Post Falls", "ID", "83854", "Coeur d'Alene Reporting Area"], ["Badger Building Center", "Kalispell", "MT", "59901", null], ["Badger Building Center", "Bonners Ferry", "ID", "83805", null], ["Elma Building Center", "Elma", "WA", "98541", null], ["Beaverhead Building Center", "Dillon", "MT", "59725", null], ["Best Built Builders Supply", "Orofino", "ID", "83544", "Nez Perce Reservation"], ["Best Built Builders Supply", "Grangeville", "ID", "83530", "Grangeville Reporting Area"], ["Best Built Builders Supply", "Kamiah", "ID", "83536", null], ["Best Built Builders Supply", "Lewiston", "ID", "83501", "Lewiston Reporting Area"], ["Browne's Home Center", "Friday Harbor", "WA", "98250", null], ["Ennis Building Center", "Ennis", "MT", "59729", "Bozeman EBAM Monitor"], ["Gerretsen Building Supply", "Roseburg", "OR", "97470", null], ["Harbor Rental and Saw", "Friday Harbor", "WA", "98250", null], ["Lake Chelan Building Supply", "Chelan", "WA", "98816", "Chelan Reporting Area"], ["Lake Chelan Building Supply", "Manson", "WA", "98831", "Chelan Reporting Area"], ["Marson and Marson Lumber", "Leavenworth", "WA", "98826", "Leavenworth Reporting Area"], ["Marson and Marson Lumber", "Wenatchee", "WA", "98801", null], ["Marson and Marson Lumber", "Cle Elum", "WA", "98922", null], ["Marson and Marson Lumber", "Ephrata", "WA", "98823", null], ["Midway Building Supply", "Tonasket", "WA", "98855", null], ["Midway Building Supply", "Republic", "WA", "99166", "Republic Monitor"], ["Midway Building Supply", "Oroville", "WA", "98844", "Tonasket Monitor"], ["Miller's Home Center", "Baker City", "OR", "97814", null], ["Miller's Home Center", "La Grande", "OR", "97850", null], ["Mount Vernon Building Center", "Mount Vernon", "WA", "98273", null], ["TAL Support Center", "Vancouver", "WA", "98684", null], ["Tum-A-Lum Lumber", "Hood River", "OR", "97031", null], ["Tum-A-Lum Lumber", "The Dalles", "OR", "97058", null], ["Tum-A-Lum Lumber", "Pendleton", "OR", "97801", null]].map(([division,city,state,zip,preferredReportingArea])=>({division,city,state,zip,preferredReportingArea}));
const file=path.join(process.cwd(),'cache','aqi-cache.json');
const norm=v=>String(v||'').toLowerCase().replace(/reporting area|monitor/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const source=x=>x.ReportingArea||x.reportingArea||x.SiteName||x.siteName||null;
const aq=x=>{for(const v of[x?.AQI,x?.aqi,x?.NowcastAQI,x?.nowcastAQI]){const n=Number(v);if(Number.isFinite(n))return n}return null};
const cat=x=>{const c=x.Category??x.category;return typeof c==='object'?(c.Name??c.name??null):(c??x.CategoryName??x.categoryName??null)};
function previous(){try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return {locations:[]}}}
async function one(l){const q=new URLSearchParams({format:'application/json',zipCode:l.zip,distance:'50',API_KEY:key});const url='https://www.airnowapi.org/aq/observation/current/zipCode/?'+q;const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status+': '+(await r.text()).slice(0,120));const all=await r.json();if(!Array.isArray(all))throw new Error('Unexpected AirNow response');const want=norm(l.preferredReportingArea),matches=want?all.filter(x=>{const a=norm(source(x));return a&&(a===want||a.includes(want)||want.includes(a))}):all,item=[...(matches.length?matches:all)].sort((a,b)=>(aq(b)??-1)-(aq(a)??-1))[0];if(!item)throw new Error('No current observation returned');return {...l,aqi:aq(item),category:cat(item)||'Observation available',pollutant:item.ParameterName||item.parameterName||null,reportingArea:source(item)||l.preferredReportingArea,lastUpdated:new Date().toISOString(),error:want&&!matches.length?'Preferred source not found; nearest ZIP result shown':null}}
(async()=>{const old=previous(),out=[];for(const l of locations){try{out.push(await one(l))}catch(e){const prior=old.locations?.find(x=>x.division===l.division&&x.city===l.city&&x.state===l.state&&String(x.zip)===l.zip);out.push(prior?{...prior,...l,error:'Update failed; retained previous cache: '+e.message}:{...l,aqi:null,category:'Unavailable',pollutant:null,reportingArea:l.preferredReportingArea,lastUpdated:null,error:e.message})}}const cache={schemaVersion:2,lastUpdated:new Date().toISOString(),reporting:out.filter(x=>x.aqi!=null).length,elevated:out.filter(x=>x.aqi>100).length,status:'Workflow completed',locations:out};fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(cache,null,2)+'\n');console.log(`Cache written: ${cache.reporting}/${out.length} reporting`);if(!cache.reporting)console.warn('No live observations returned; diagnostic cache was still written.')})().catch(e=>{console.error(e);process.exit(1)});
